# This is a basic workflow to help you get started with Actions

name: ProjectBuild
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
        submodules: true

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
    
    - name: Restore NuGet packages
      run: nuget restore Another-Mirai-Native2.sln 
      
    - name: Restore DllExport    
      run: .\DllExport -action Restore
      
    - name: Run MSBuild
      run: msbuild Another-Mirai-Native2.sln -p:Configuration=Debug -p:Platform=x86
      
    - name: Build Publish Result
      run: .\Release.bat 

    - name: Upload a Build Artifact(Console_net48)
      uses: actions/upload-artifact@v4
      with:
             name: Minimal_Console
             path: build\Console\net48\

    - name: Upload a Build Artifact(Blazor)
      uses: actions/upload-artifact@v4
      with:
             name: WebUI
             path: build\Web\

    - name: Upload a Build Artifact(WPF_net8)
      uses: actions/upload-artifact@v4
      with:
             name: WPF_net8
             path: build\WPF\net8\

    - name: Upload a Build Artifact(WPF_net48)
      uses: actions/upload-artifact@v4
      with:
             name: WPF_net48
             path: build\WPF\net48\
